Update glpass

diff --git a/.local/scripts/glpass b/.local/scripts/glpass
--- a/.local/scripts/glpass
+++ b/.local/scripts/glpass
@@ -1,158 +1,201 @@
-#!/usr/bin/env run-cargo-script
+#!/usr/bin/env bash
 
-//! ```cargo
-//! [package]
-//! version = "0.1.0"
-//!
-//! [dependencies]
-//! structopt = "0.3"
-//! shellfn = "0.1"
-//! ```
+set -e
 
-const NAME: &str = "glpass";
-const NONE: &str = "<NONE>";
+# Set some variables
+LP=lpass
+SCRIPT_NAME=$(basename $0)
+C_RED=$(tput setaf 1)
+C_GREEN=$(tput setaf 2)
+C_YELLOW=$(tput setaf 3)
+C_PINK=$(tput setaf 5)
+C_BOLD=$(tput bold)
+C_RESET=$(tput sgr0)
 
-extern crate structopt;
-use structopt::StructOpt;
+usage() {
+    cat <<EOF
+Usage: $SCRIPT_NAME COMMAND [OPTIONS]
+Fetch lastpass secrets.
 
-extern crate shellfn;
-use shellfn::shell;
-use std::error::Error;
+Supported commands are:
+  login
+  logout
+  ssh
+  token
+  credentials
 
-/// Quick and easy integration with LastPass
-#[derive(StructOpt, Debug, PartialEq)]
-#[structopt(name = NAME)]
-struct Opts {
-    #[structopt(short, long, global = true, help = "Id of LastPass entry")]
-    id: Option<String>,
+Examples:
 
-    #[structopt(subcommand)]
-    cmd: Cmd,
-}
+  Login to lpass:
+    $ $SCRIPT_NAME login -le <EMAIL> -lk <KEY>
 
-#[derive(StructOpt, Debug, PartialEq)]
-enum Cmd {
-    field(FieldOpts),
-    login(LoginOpts),
-}
+  Add ssh key to ssh-agent:
+    $ $SCRIPT_NAME ssh -s
 
-/// Retrieve a field from LastPass entries
-#[derive(StructOpt, Debug, PartialEq)]
-struct FieldOpts {
-    #[structopt(short, long, help = "Search filter", default_value = ".")]
-    search: String,
+  Fetch token:
+    $ $SCRIPT_NAME token
 
-    #[structopt(name = "FIELDNAME")]
-    field_name: String,
-}
+  Fetch token with id:
+    $ $SCRIPT_NAME token -i xaori6o43fhmyh4zzc34nkayee
 
-/// Login to a service using LastPass
-#[derive(StructOpt, Debug, PartialEq)]
-struct LoginOpts {
-    #[structopt(short, long, help = "Search filter [defaults to the service name]")]
-    search: Option<String>,
+  Fetch a website login:
+    $ $SCRIPT_NAME credentials
 
-    #[structopt(name = "SERVICE_NAME", help = "Valid values are: ssh, docker")]
-    service_name: String,
-}
+  Logout from 1password:
+    $ $SCRIPT_NAME logout
 
-fn main() {
-    // Parse opts
-    let opts = Opts::from_args();
-
-    // Setup search
-    let search = match &opts.cmd {
-        Cmd::field(c) => c.search.as_str(),
-        Cmd::login(c) => match &c.search {
-            Some(s) => s.as_str(),
-            None => c.service_name.as_str(),
-        },
-    };
-
-    // Setup ID
-    let id = match opts.id {
-        Some(id) => id,
-        None => find_id(search).expect("failed searching for id"),
-    };
-    let id = id.trim();
-
-    // Run command
-    let result = match &opts.cmd {
-        Cmd::field(ref c) => cmd_field(id, c.field_name.as_str()),
-        Cmd::login(ref c) => cmd_login(id, c.service_name.as_str()),
-    };
-
-    // Handle the result
-    match result {
-        Ok(s) => print!("{}", s),
-        Err(e) => eprintln!("{}", e),
-    }
-}
-
-fn cmd_field(id: &str, field_name: &str) -> Result<String, Box<Error>> {
-    let result = match field_name {
-        "id" => Ok(id.to_string()),
-        "name" | "password" | "username" | "notes" => get_field(id, field_name),
-        _ => get_custom_field(id, field_name),
-    };
-    Ok(result?)
-}
-
-fn cmd_login(id: &str, service_name: &str) -> Result<String, Box<Error>> {
-    let result = match service_name {
-        "docker" => login_docker(id),
-        "ssh" => login_ssh(id),
-        _ => err_msg(format!("{} is not a valid service name", service_name)),
-    };
-    Ok(result?)
-}
-
-#[shell]
-fn find_id(search: &str) -> Result<String, Box<Error>> {
-    r#"
-    lpass ls --sync=no | grep $SEARCH | fzf --header='Select item ...' | grep -o -e 'id: [0-9]*' | awk '{print $2}'
-    "#
-}
-
-#[shell]
-fn get_field(id: &str, field: &str) -> Result<String, Box<Error>> {
-    r#"
-    lpass show --sync=no $ID --$FIELD
-    "#
-}
-
-#[shell]
-fn get_custom_field(id: &str, field: &str) -> Result<String, Box<Error>> {
-    r#"
-    lpass show --sync=no $ID --field="$FIELD"
-    "#
-}
-
-#[shell]
-fn login_ssh(id: &str) -> Result<String, Box<Error>> {
-    r#"
-    TMP=$(mktemp)
-    cat << EOF > $TMP
-    #!/bin/sh    
-    set -e
-    glpass -i $ID field 'Passphrase'
+Options:
+  -i,  --id=          Skip searching and provide ID of item
+  -s,  --ssh-add      Add to ssh agent (only works with ssh-key)
+  -le, --login-email  Email to login with
+  -h,  --help         Print usage
 EOF
-    chmod +x $TMP
-    export SSH_ASKPASS=$TMP
-    glpass -i $ID field 'Private Key' | ssh-add - && rm $TMP
-    "#
+    exit 2
 }
 
-#[shell]
-fn login_docker(id: &str) -> Result<String, Box<Error>> {
-    r#"
-    glpass -i $ID field password | docker login --username $(glpass -i $ID field username) --password-stdin 2> /dev/null
-    "#
+sh-log-lines() {
+    for a in "$@"; do
+        printf "\n  $a" 1>&2
+    done
+    printf "\n" 1>&2
 }
 
-fn err_msg(msg: String) -> Result<String, Box<Error>> {
-    return Err(Box::new(std::io::Error::new(
-        std::io::ErrorKind::Other,
-        msg,
-    )));
+sh-log-info() {
+    printf "${C_GREEN}INFO${C_RESET}: $1" 1>&2
+    sh-log-lines "${@:2}"
 }
+
+sh-log-warn() {
+    printf "${C_YELLOW}WARN${C_RESET}: $1" 1>&2
+    sh-log-lines "${@:2}"
+}
+
+sh-log-error() {
+    printf "${C_RED}ERROR${C_RESET}: $1" 1>&2
+    sh-log-lines "${@:2}"
+    exit 1
+}
+
+sh-string-highlight() {
+    d=""
+    for a in "$@"; do
+        printf "${C_BOLD}${C_PINK}$d$a${C_RESET}"
+        d=" "
+    done
+}
+
+lp-select-generic() {
+    $LP ls --sync=no | \
+        tr '[:upper:]' '[:lower:]' | \
+        grep "$1" | \
+        sort | \
+        fzf --header 'Select item!' | \
+        grep -o -E '\[id: .*\]' | \
+        awk '{print $2}' | \
+        sed 's%]%%g'
+}
+
+# Check for dependencies
+command -v jq &>/dev/null || sh-log-error "Binary jq not found!" "Install jq before using this script!"
+command -v fzf &>/dev/null || sh-log-error "Binary fzf not found!" "Install fzf before using this script!"
+command -v $LP &>/dev/null || sh-log-error "Binary $LP not found!" "Install $LP before using this script!"
+
+# Input arguments
+COMMAND=""
+SSH_ADD="false"
+ID=""
+LOGIN_EMAIL=""
+
+# Parse input arguments
+while [ "$#" -gt 0 ]; do
+    case $1 in
+    -h | --help)
+        usage
+        ;;
+    -s | --ssh-add)
+        SSH_ADD="true"
+        ;;
+    -i)
+        shift
+        ID="$1"
+        ;;
+    --id=*)
+        ID=$(echo $1 | awk '{split($0,r,"="); print r[2]}')
+        ;;
+    -le)
+        shift
+        LOGIN_EMAIL="$1"
+        ;;
+    --login-email=*)
+        LOGIN_EMAIL=$(echo $1 | awk '{split($0,r,"="); print r[2]}')
+        ;;
+    *)
+        COMMAND="$1"
+        ;;
+    esac
+    shift
+done
+
+# Verify command
+case $COMMAND in
+ssh | token | credentials | login | logout) ;;
+*)
+    [ "$COMMAND" == "" ] && usage
+    sh-log-error "Unsupported command: $COMMAND"
+    ;;
+esac
+
+# Handle login
+if [ "$COMMAND" == "login" ]; then
+    [ "$LOGIN_EMAIL" == "" ] && sh-log-error "Login email not provided" "Log in by running: $(sh-string-highlight "$SCRIPT_NAME login -le <EMAIL> -lk <KEY>")"
+    $LP login $LOGIN_EMAIL
+    exit 0
+fi
+
+# Handle logout
+if [ "$COMMAND" == "logout" ]; then
+    $LP logout
+    exit 0
+fi
+
+# Test if session is valid
+$LP status | grep -v "Not logged in." 2>&1 > /dev/null || sh-log-error "Not logged in to Lastpass!" "Log in by running: $(sh-string-highlight "$SCRIPT_NAME login -le <EMAIL>")"
+
+# Get ID
+if [ "$ID" == "" ]; then
+    case $COMMAND in
+    ssh)
+        ID=$(lp-select-generic ssh)
+        ;;
+    token)
+        ID=$(lp-select-generic token)
+        ;;
+    *)
+        ID=$(lp-select-generic)
+        ;;
+    esac
+fi
+
+# Verify ID is selected
+[ "$ID" == "" ] && sh-log-error "No item selected!"
+
+# Fetch fields
+case $COMMAND in
+ssh)
+    if [ "$SSH_ADD" == "true" ]; then
+        $LP show --sync=no $ID --field "Private Key" | ssh-add -
+    else
+        $LP show --sync=no $ID --field "Private Key"
+    fi
+    ;;
+token)
+    $LP show --sync=no $ID --password
+    ;;
+credentials)
+    $LP show --sync=no $ID --username
+    $LP show --sync=no $ID --password
+    ;;
+*)
+    sh-log-error "Unexpected state!"
+    ;;
+esac
